name: Clippy

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: â¬ Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: ðŸ’¾ Cache
        uses: actions/cache@v4.2.4
        with:
          path: target/
          key: target

      - name: ðŸ¦€ Rust setup
        run: |
          rustup default stable
          rustup update

      - name: ðŸ› ï¸ Install dependencies
        run: sudo apt-get install -y libudev-dev

      - name: ðŸ“Ž Clippy
        env:
          SKIP_GLTF_EXPORT: true
        run: cargo clippy --fix

      - name: ðŸ§¹ RustFmt
        env:
          SKIP_GLTF_EXPORT: true
        run: cargo fmt --verbose --all

      - name: ðŸ‘€ Checking for changes ...
        id: changes
        run: echo "status=$(git status --porcelain | wc -l)" >> "$GITHUB_OUTPUT"

      - name: â« Push changes
        if: ${{ steps.changes.outputs.status != '' && steps.changes.outputs.status > 0 }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "Changes detected. Committing and pushing..."

          # Print status to visually see what changed
          git status

          git config --global user.name '@SakulFlee | Lukas Weber'
          git config --global user.email 'dev@sakul-flee.de'

          git add --all
          git commit -a -m "Automated commit by CI"
          git push "https://${GH_PAT}@github.com/${{ github.repository }}.git"

          echo "Git push completed."
